#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-py
Version  : 1.8.0
Release  : 60
URL      : https://files.pythonhosted.org/packages/f1/5a/87ca5909f400a2de1561f1648883af74345fe96349f34f737cdfc94eba8c/py-1.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f1/5a/87ca5909f400a2de1561f1648883af74345fe96349f34f737cdfc94eba8c/py-1.8.0.tar.gz
Summary  : library with cross-python path, ini-parsing, io, code, log facilities
Group    : Development/Tools
License  : MIT
Requires: deprecated-py-license = %{version}-%{release}
Requires: deprecated-py-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pytest
BuildRequires : setuptools-legacypython
BuildRequires : setuptools-python
BuildRequires : setuptools_scm
BuildRequires : setuptools_scm-legacypython

%description
.. image:: https://img.shields.io/pypi/v/py.svg
:target: https://pypi.org/project/py

%package legacypython
Summary: legacypython components for the deprecated-py package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-py package.


%package license
Summary: license components for the deprecated-py package.
Group: Default

%description license
license components for the deprecated-py package.


%package python
Summary: python components for the deprecated-py package.
Group: Default

%description python
python components for the deprecated-py package.


%prep
%setup -q -n py-1.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554325144
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test --verbose ||:
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-py
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-py/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-py/LICENSE

%files python
%defattr(-,root,root,-)
